#!/usr/bin/env python3

try:
    # svg2tikz installed into system's python path?
    import svg2tikz
except ImportError:
    # if not, have a look into default directory
    import sys, os

    sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + "/../")
    import svg2tikz

from svg2tikz.tikz_export import main_cmdline

if __name__ == "__main__":
    main_cmdline()
